Repository gitpod-io/gitpod-test-repo, pull requests merged in 2021-10, with the labels that each got.

#193 Update demo.txt
  demo.txt
Labels: lgtm, approved, size/XS, release-note-none

#194 Update demo.txt
  demo.txt
Labels: lgtm, approved, size/XS, release-note-none

#195 [changelog] use latest docker image
  .werft/changelog.yaml
Labels: lgtm, approved, size/XS, release-note-none

#196 changelog test
  CHANGELOG.md
  miau.txt
Labels: lgtm, approved, size/XS, release-note

#197 [changelog] updated changelog
  CHANGELOG.md
Labels: lgtm, approved, size/S, release-note-none
